In [37]:
import pandas as pd
import numpy as np

In [38]:
df = pd.read_excel("교차로 접근로별 교통량_이마트.xlsx", sheet_name="2303")
df

          접근로명                   시간  교통량  평균속도  보행자수
0     금강120동방향  2023-03-01 00:00:00  309    82    25
1     금강120동방향  2023-03-01 01:00:00  242    87    26
2     금강120동방향  2023-03-01 02:00:00  161    85    11
3     금강120동방향  2023-03-01 03:00:00  163    79     5
4     금강120동방향  2023-03-01 04:00:00  195    76     8
...        ...                  ...  ...   ...   ...
2971    중앙공원방향  2023-03-31 19:00:00  899    33    36
2972    중앙공원방향  2023-03-31 20:00:00  871    32    29
2973    중앙공원방향  2023-03-31 21:00:00  626    32    46
2974    중앙공원방향  2023-03-31 22:00:00  441    36    20
2975    중앙공원방향  2023-03-31 23:00:00  316    36    27

[2976 rows x 5 columns]

In [39]:
df_W1 = df[df['접근로명']=='보차도2교방향']
df_W1 = df_W1.reset_index(drop=True)
len(df_W1)

744

In [40]:
df_W1['출근시간'] = df_W1['시간'].str[11:]

In [41]:
len(df_W1)

744

In [42]:
df_W1

        접근로명                   시간   교통량  평균속도  보행자수      출근시간
0    보차도2교방향  2023-03-01 00:00:00   216    67    21  00:00:00
1    보차도2교방향  2023-03-01 01:00:00   178    68    22  01:00:00
2    보차도2교방향  2023-03-01 02:00:00   126    65    11  02:00:00
3    보차도2교방향  2023-03-01 03:00:00   131    68     6  03:00:00
4    보차도2교방향  2023-03-01 04:00:00   119    70     7  04:00:00
..       ...                  ...   ...   ...   ...       ...
739  보차도2교방향  2023-03-31 19:00:00  1230    32   189  19:00:00
740  보차도2교방향  2023-03-31 20:00:00  1108    33   145  20:00:00
741  보차도2교방향  2023-03-31 21:00:00   695    33   110  21:00:00
742  보차도2교방향  2023-03-31 22:00:00   436    38    76  22:00:00
743  보차도2교방향  2023-03-31 23:00:00   314    37    78  23:00:00

[744 rows x 6 columns]

In [43]:
df_W1.drop(columns=['시간'], inplace=True)

In [44]:
six = df_W1[(df_W1['출근시간'] == '06:00:00')]
seven = df_W1[(df_W1['출근시간'] == '07:00:00')]
eight = df_W1[(df_W1['출근시간'] == '08:00:00')]

In [45]:
max_six = six['교통량'].max()
max_seven = seven['교통량'].max()
max_eight = eight['교통량'].max()
max_six, max_seven, max_eight

(286, 485, 679)

In [46]:
mean_six = six['교통량'].mean()
mean_seven = seven['교통량'].mean()
mean_eight = eight['교통량'].mean()
mean_six, mean_seven, mean_eight

(200.5483870967742, 353.6774193548387, 502.06451612903226)

In [47]:
max_six + max_seven + max_eight

1450

In [48]:
mean_six + mean_seven + mean_eight

1056.2903225806451